Models/ErrorViewModel.cs
using System;

namespace weektime.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using weektime.Models;

namespace weektime.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginOrRegController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using weektime.Models;
using Microsoft.AspNetCore.Http;

namespace weektime.Controllers
{
    public class LoginOrRegController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Register()
        {
            ViewData["Message"] = "Your application description page.";
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "关于我";
}
<section class="maincta">
    <div class="layer">
    </div>
    <div class="container-fluid hero">
        <div class="major-header">
            <div class="row">
                <div class="col-sm-11">
                       <div class="goodbye">
                         <div class="row">
                            <div class="col-sm-12">
                                <h1>StartLea</h1>
                            </div>
                        </div>
                    </div>
                 <div class="row">
                    <div class="valueprop">
                        <div class="col-sm-12">
                            <p>E-mail:</p>
                        </div>
                        <div class="col-sm-12">
                            <p>博客:</p>
                        </div>
                    </div>
                </div> 
                </div>
            </div>
        </div>
    </div>
</section>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "联系我";
}
<di class="maincontent">
    <div class="top-mid">

    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "主页";
}
<section class="maincta">
    <div class="layer">
    </div>
    <div class="container-fluid hero">
        <div class="major-header">
            <div class="row">
                <div class="col-sm-11">
                       <div class="goodbye">
                         <div class="row">
                            <div class="col-sm-12">
                                <h1>WeekTime</h1>
                            </div>
                        </div>
                    </div>
                 <div class="row">
                    <div class="valueprop">
                        <div class="col-sm-12">
                            <p>休闲社区，有什么好吃的好喝的好玩的,<span class="lineza"></span>统统给我晒出来~</p>
                        </div>
                    </div>
                </div>
                    <div class="row">
                        <div class="ttopbutton col-md-6">
                            <a asp-controller="LoginOrReg" asp-action="Register">
                                <button class="btn btn-divi">免费注册</button>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-1"> 
                </div>
            </div>
        </div>
    </div>
</section>

Views/LoginOrReg/Login.cshtml
@{
    ViewData["Title"] = "主页";
}
<section class="maincta">
    <div class="layer">
    </div>
    <div class="container-fluid hero">
        <div class="major-header">
            <div class="row">
                <div class="col-sm-11">
                       <div class="goodbye">
                         <div class="row">
                            <div class="col-sm-12">
                                <h1>WeekTime</h1>
                            </div>
                        </div>
                    </div>
                 <div class="row">
                    <div class="valueprop">
                        <div class="col-sm-12">
                            <p>休闲社区，有什么好吃的好喝的好玩的,<span class="lineza"></span>统统给我晒出来~</p>
                        </div>
                    </div>
                </div>
                    <div class="row">
                        <div class="ttopbutton col-md-6">
                            <a asp-action="Register">
                                <button class="btn btn-divi">免费注册</button>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-1"> 
                </div>
            </div>
        </div>
    </div>
</section>

Views/LoginOrReg/Register.cshtml
@{
    ViewData["Title"] = "主页";
}
<section class="maincta">
    <div class="layer">
    </div>
    <div class="container-fluid hero">
        <div class="major-header">
            <div class="row">
                <div class="col-sm-11">
                       <div class="goodbye">
                         <div class="row">
                            <div class="col-sm-12">
                                <h1>WeekTime</h1>
                            </div>
                        </div>
                    </div>
                 <div class="row">
                    <div class="valueprop">
                        <div class="col-sm-12">
                            <p>休闲社区，有什么好吃的好喝的好玩的,<span class="lineza"></span>统统给我晒出来~</p>
                        </div>
                    </div>
                </div>
                    <div class="row">
                        <div class="ttopbutton col-md-6">
                            <a asp-action="Register">
                                <button class="btn btn-divi">免费注册</button>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-1"> 
                </div>
            </div>
        </div>
    </div>
</section>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - weektime</title>
    <link rel="icon" href="favicon.ico" type="image/x-icon" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-theme.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> 菜单 <i class="fa fa-bars"></i>
            </button>
            </div>
             <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav navbar-right">
                      <li><a asp-controller="Home" asp-action="Index">主页</a></li>
                      <li><a asp-controller="Home" asp-action="About">关于我</a></li>
                      <li><a asp-controller="Home" asp-action="Contact">联系我</a></li>
                      <li>
                          <a asp-controller="LoginOrReg" asp-action="Login" >
                              <button class="btn btn-divi-top">登录</button>
                          </a>
                      </li>
                  </ul>
             </div>
        </div>
    </nav>
    @RenderBody()
    @RenderSection("Scripts", required: false)
</body>
</html>